# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88424374dd4489ae702113dea6116e80d2d16e190c696fb72aea7a3dba601eeb6de32fda6f80003ec64d24c831a9b77250bba2c27aabb5ff67beaf341f385fac

test:
  secret_key_base: b276e0ad90eb3d6dc4ae2f6e8d5e45ed244d3b3fcbace9c717d40b2c0e60e62b1a894c69a8832d653f2974416d90d9ff411118a8b53a0b132df784eab6df6e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
